version: 1
services:
  - type: web
    name: ollama-fastapi-app
    env: python
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
    startCommand: |
      # Start the Ollama Docker container and FastAPI app
      bash start.sh
    autoDeploy: true
    port: 8080
