runtime: python311

env_variables:
  OLLAMA_SERVER_URL: "http://localhost:11434"  # Adjust if needed

entrypoint: bash start.sh

instance_class: F4  # You can adjust this based on your needs

env: flex

# Optional: You can set additional environment variables if needed for deployment.
